# Generated by Django 5.2.2 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_order_items_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category_budgets',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
